name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: 'private'
        registries: '<aws_account_id>.dkr.ecr.<region>.amazonaws.com'
        mask-password: true

    - name: Build Docker image
      run: docker build -t <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:latest .

    - name: Push Docker image to ECR
      run: docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:latest


