name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: 'private'
        registry: '<410454990341>.dkr.ecr.<us-west-1>.amazonaws.com'

    - name: Build Docker image
      run: docker build -t <410454990341>.dkr.ecr.<us-west-1>.amazonaws.com/<express-app-02>:latest .

    - name: Push Docker image to ECR
      run: 410454990341>.dkr.ecr.<us-west-1>.amazonaws.com/<express-app-02>:latest


